name: Linter Check
on: [push, pull_request]

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: install linter
        run: sudo apt install pylint

      - name: lint
        run: pylint "manage_externals/manic"